name: Generate ASCII Artwork 

on: push 

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y 

            - name: list repo files
              run: ls -lrta

            - name: Execute shell script 
              run: | 
                chmod +x ascii-script.sh
                ./ascii-script.sh