name: Multiple jobs
on: push 

jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps: 
            - name: Install cowsay Program 
              run: sudo apt install cowsay -y 

            - name: Execute cowsay CMD
              run: cowsay -f dragon "RUN for cover, I'm a Dragon" >> dragon.txt

            - name: Upload Dragon text file
              uses: actions/upload-artifact@v3
              with: 
                name: dragon-text-file
                path: dragon.txt
    
    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v3
              with: 
                path: dragon.txt
            
            - name: Test file exists
              run: grep -i "dragon" dragon.txt
    
    deploy_job_3:
        runs-on: ubuntu-latest
        needs: test_job_2
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v3
              with: 
                path: dragon.txt

            - name: Read File
              run: cat dragon.txt
            
            - name: Deploy 
              run: echo deploying ... 